DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;

USE bd;

CREATE TABLE JUGADOR (
	IDJ INT PRIMARY KEY NOT NULL,				  
	USERNAME CHAR(60),
	CONT CHAR(60)
)ENGINE=InnoDB;

CREATE TABLE PARTIDA (
	ID INT PRIMARY KEY NOT NULL,
	GANADOR VARCHAR (60),
	FECHA CHAR(10),
	HORA INT,
	DURACION INT
)ENGINE=InnoDB;

CREATE TABLE PUNTUACION (
	ID_J INT NOT NULL,
	ID_P INT NOT NULL,
	PUNTOS INT NOT NULL,
	FOREIGN KEY (ID_J) REFERENCES JUGADOR(IDJ),
	FOREIGN KEY (ID_P) REFERENCES PARTIDA(ID)
)ENGINE=InnoDB;

INSERT INTO JUGADOR VALUES (1, 'Pepito', 'BARNA');
INSERT INTO JUGADOR VALUES (2, 'Juanito', 'castefa');
	
INSERT INTO PARTIDA VALUES (1,'Pepito','10/10/10',16,20);
INSERT INTO PARTIDA VALUES (2,'Juanito','06/54/45',15,56);
	
INSERT INTO PUNTUACION VALUES (1,1,200);
INSERT INTO PUNTUACION VALUES (1,2,122);
INSERT INTO PUNTUACION VALUES (2,1,45);
INSERT INTO PUNTUACION VALUES (2,2,341);
